[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate && pip install -r src/requirements.txt"
]

[start]
cmd = "cd src && . /opt/venv/bin/activate && uvicorn app:app --host 0.0.0.0 --port $PORT" 