[phases.setup]
aptPkgs = ["python3", "python3-pip", "python3-venv"]

[phases.install]
cmds = [
  "pip install -r src/requirements.txt"
]

[start]
cmd = "cd src && uvicorn app:app --host 0.0.0.0 --port $PORT" 