[build]
builder = "DOCKERFILE"
dockerfile = "Dockerfile"

[deploy]
healthcheck_path = "/"
healthcheck_timeout = 10
startCommand = "cd src && uvicorn app:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.envs]
PYTHON_VERSION = "3.9" 