name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Render
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f src/requirements.txt ]; then pip install -r src/requirements.txt; fi
          
      - name: Test with Docker
        run: |
          docker build -t web-crawler .
          docker run -d -p 8016:8016 --name web-crawler-test web-crawler
          sleep 5
          curl -f http://localhost:8016/ || exit 1
          docker stop web-crawler-test
          docker rm web-crawler-test
        
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }} 